"""Telecom provider protocol and shared data types — Phase 4.

Defines:
- ``CallEvent``: immutable dataclass representing a single event emitted by a
  telecom provider (e.g. RINGING, ANSWERED, COMPLETED).
- ``TelecomProvider``: structural protocol that all provider implementations must
  satisfy.  Uses ``runtime_checkable`` so we can ``isinstance``-check mock stubs.

Design note: providers emit events *asynchronously* via a callback/queue.
The event ingestor (``app/events/ingestor.py``) is the single consumer of
these events.  Providers must NOT write directly to the database.
"""

from __future__ import annotations

import queue
import uuid
from dataclasses import dataclass, field
from datetime import datetime
from typing import Callable, Protocol, runtime_checkable


# Valid event types a provider may emit.
VALID_EVENT_TYPES: frozenset[str] = frozenset(
    {"RINGING", "ANSWERED", "CONNECTED", "COMPLETED", "FAILED"}
)


@dataclass(frozen=True)
class CallEvent:
    """An event emitted by a telecom provider for a specific call.

    Attributes:
        event_id:   Globally unique event identifier (UUID4 string).
                    Used by the ingestor for idempotency deduplication.
        call_id:    The call this event belongs to.
        event_type: One of RINGING, ANSWERED, CONNECTED, COMPLETED, FAILED.
        timestamp:  UTC wall-clock time when the event was generated by the provider.
    """

    call_id: str
    event_type: str
    timestamp: datetime
    event_id: str = field(default_factory=lambda: str(uuid.uuid4()))

    def __post_init__(self) -> None:
        if self.event_type not in VALID_EVENT_TYPES:
            raise ValueError(
                f"Invalid event_type {self.event_type!r}; "
                f"must be one of {VALID_EVENT_TYPES}"
            )


@runtime_checkable
class TelecomProvider(Protocol):
    """Protocol that all telecom provider implementations must satisfy.

    The provider's job is to:
    1. Initiate a call (``initiate_call``).
    2. Emit :class:`CallEvent` objects into the ``event_queue`` as the call
       progresses through its lifecycle.
    3. Report health statistics so the SafetyController circuit breaker can
       make informed decisions.

    All provider implementations must be thread-safe.
    """

    #: Shared queue into which the provider pushes CallEvent objects.
    event_queue: queue.Queue  # type: ignore[type-arg]

    def initiate_call(self, call_id: str, phone: str) -> None:
        """Begin dialling ``phone`` for the given ``call_id``.

        Events will be pushed into ``self.event_queue`` asynchronously.

        Args:
            call_id: The ID of the call record in the database.
            phone:   The E.164 phone number to dial.
        """
        ...

    @property
    def name(self) -> str:
        """Human-readable provider name (e.g. 'mock_a')."""
        ...

    def get_health(self) -> dict:
        """Return a snapshot of provider health metrics.

        Keys should include at minimum:
        - ``timeout_rate``: fraction of calls that timed out (float).
        - ``error_rate``:   fraction of calls that errored (float).
        - ``is_healthy``:   whether the provider is considered up (bool).
        """
        ...
